# action.yml
name: 'Culinary Class Wars PR Agent'
description: 'AI based Culinary Class Wars Concept PR Agent'
inputs:
  gemini_api_key:
    description: 'Gemini API Key'
    required: true
  github_token:
    description: 'Gemini API Key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Reviewer Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}/scripts
        npm init -y
        npm install @actions/github

    - name: Run Culinary Review
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ACTION_PATH: ${{ github.action_path }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        BASE_REF: ${{ github.event.pull_request.base.ref }}
      run: |
          node ${{ github.action_path }}/scripts/culinary_review.js
