# action.yml
name: 'Culinary Class Wars PR Agent'
description: 'AI based Culinary Class Wars Concept PR Agent'
inputs:
  gemini_api_key:
    description: 'Gemini API Key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run Culinary Review
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
      run: |
        node ${{ github.action_path }}/scripts/culinary_review.js